---

# This playbook will do the following:
# Set up Kubernetes (K8S) and install necessary packages

- hosts: MyChameleonVMs
  remote_user: cc
  collections:
    - openstack.cloud
  tasks:
  - name: apt-get update
    become: yes
    apt:
      update_cache: yes
  - name: copy k8s-setup script
    copy:
      src: k8s-setup.sh
      dest: /home/cc/k8s-setup.sh
  - name: run k8s-setup script
    ansible.builtin.command: sh /home/cc/k8s-setup.sh
  - name: apt-get update
    become: yes
    apt:
      update_cache: yes
  - name: install k8s packages
    become: yes
    apt:
      pkg:
      - kubeadm
      - kubelet
      - kubectl
      - kubernetes-cni
      state: present
...
