---
# .yaml file for couchdb service

apiVersion: v1
kind: Service
metadata:
  name: couchdb-svc
spec:
  type: NodePort
  selector:
    app: couchdb-svc-app
  ports:
    - name: couchdb-svc-port
      protocol: TCP
      port: 5984
      targetPort: 5984
      nodePort: 30001
...
