---
# deployment spec for pyzmq server-side

apiVersion: apps/v1
kind: Deployment         
metadata:
  name: pyzmq-deployment
spec:
  selector:
    matchLabels:
      app: pyzmq-svc-app
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: pyzmq-svc-app
    spec:
      containers:
      - name: pyzmq
        image: 129.114.25.77:5000/pyzmq:latest
        ports:
        - containerPort: 5556
        command: ["python3"]
        args: ["pyzmq-server.py"]

...
